const STORAGE_KEY="tabiwaku-v1-4";
const PREVIOUS_KEYS=["tabiwaku-v1-3","tabiwaku-v1-2","tabiwaku-v1-1"];
const TYPES={move:{label:"移動",icon:"🚗"},sight:{label:"観光",icon:"📍"},food:{label:"食事",icon:"🍴"},stay:{label:"宿泊",icon:"🏨"},other:{label:"その他",icon:"●"}};
const TEMPLATES=["07:00","10:00","13:00","16:00"];
const el={title:document.getElementById("tripTitle"),date:document.getElementById("tripDate"),addDay:document.getElementById("addDayButton"),days:document.getElementById("daysEditor"),previewTitle:document.getElementById("previewTitle"),previewDate:document.getElementById("previewDate"),countdown:document.getElementById("countdown"),empty:document.getElementById("emptyPreview"),timeline:document.getElementById("timeline"),status:document.getElementById("saveStatus")};
let trip=loadTrip();let statusTimer;
renderAll();
el.title.addEventListener("input",function(){trip.title=el.title.value;saveAndPreview()});
el.date.addEventListener("input",function(){trip.date=el.date.value;saveAndPreview()});
el.addDay.addEventListener("click",function(){trip.days.push(createDay());saveAndRender()});
document.querySelectorAll(".tab-button").forEach(function(button){button.addEventListener("click",function(){switchView(button.dataset.view)})});
function uid(){return window.crypto&&crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2)}
function createSchedule(time=""){return{id:uid(),type:"sight",time:time,place:""}}
function createDay(){return{id:uid(),schedules:[createSchedule()]}}
function emptyTrip(){return{title:"",date:"",days:[createDay()]}}
function normalize(data){if(!data||!Array.isArray(data.days))return emptyTrip();const days=data.days.length?data.days:[createDay()];days.forEach(function(day){if(!Array.isArray(day.schedules)||!day.schedules.length)day.schedules=[createSchedule()];day.schedules.forEach(function(s){s.id=s.id||uid();s.type=TYPES[s.type]?s.type:"sight";s.time=typeof s.time==="string"?s.time:"";s.place=typeof s.place==="string"?s.place:""})});return{title:typeof data.title==="string"?data.title:"",date:typeof data.date==="string"?data.date:"",days:days}}
function loadTrip(){for(const key of [STORAGE_KEY].concat(PREVIOUS_KEYS)){const raw=localStorage.getItem(key);if(raw){try{return normalize(JSON.parse(raw))}catch(error){console.error("保存データ読込失敗",error)}}}return emptyTrip()}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(trip));el.status.textContent="保存しました";clearTimeout(statusTimer);statusTimer=setTimeout(function(){el.status.textContent="自動保存"},900)}
function saveAndRender(){save();renderEditor();renderPreview()}function saveAndPreview(){save();renderPreview()}
function renderAll(){el.title.value=trip.title;el.date.value=trip.date;renderEditor();renderPreview()}
function renderEditor(){el.days.replaceChildren();trip.days.forEach(function(day,dayIndex){const card=node("section","day-card");const heading=node("div","day-heading");const title=node("h3","","DAY "+(dayIndex+1));const actions=node("div","day-actions");if(trip.days.length>1)actions.appendChild(button("この日を削除","button button-danger",function(){trip.days.splice(dayIndex,1);saveAndRender()}));heading.append(title,actions);const list=node("div","schedule-list");day.schedules.forEach(function(schedule,index){list.appendChild(renderRow(day,schedule,index))});const add=button("＋ 予定を追加","button button-primary add-schedule-full",function(){const previous=findLastTime(day);day.schedules.push(createSchedule(previous?addMinutes(previous,30):""));saveAndRender()});card.append(heading,list,add);el.days.appendChild(card)})}
function renderRow(day,schedule,index){const wrap=node("div","");const row=node("div","schedule-row");const type=document.createElement("select");type.className="schedule-type";type.setAttribute("aria-label","予定の種別");Object.keys(TYPES).forEach(function(key){const op=document.createElement("option");op.value=key;op.textContent=TYPES[key].icon+" "+TYPES[key].label;op.selected=schedule.type===key;type.appendChild(op)});type.addEventListener("change",function(){schedule.type=type.value;saveAndPreview()});const minus=button("−","step-button minus",function(){schedule.time=addMinutes(schedule.time||"09:00",-15);saveAndRender()});const time=document.createElement("input");time.type="time";time.className="time-input";time.step="300";time.value=schedule.time;time.setAttribute("aria-label","時刻");time.addEventListener("input",function(){schedule.time=time.value;saveAndPreview()});const plus=button("＋","step-button plus",function(){schedule.time=addMinutes(schedule.time||"09:00",15);saveAndRender()});const place=document.createElement("input");place.type="text";place.className="schedule-place";place.placeholder="目的地・予定";place.value=schedule.place;place.setAttribute("aria-label","目的地・予定");place.addEventListener("input",function(){schedule.place=place.value;saveAndPreview()});const del=button("×","delete-button",function(){if(day.schedules.length===1){schedule.type="sight";schedule.time="";schedule.place=""}else day.schedules.splice(index,1);saveAndRender()});del.title="この予定を削除";row.append(type,minus,time,plus,place,del);const templates=node("div","time-templates");TEMPLATES.forEach(function(value){templates.appendChild(button(value,"template-button",function(){schedule.time=value;saveAndRender()}))});wrap.append(row,templates);return wrap}
function findLastTime(day){for(let i=day.schedules.length-1;i>=0;i--){if(day.schedules[i].time)return day.schedules[i].time}return""}
function addMinutes(value,minutes){const p=value.split(":").map(Number);let total=(p[0]*60+p[1]+minutes+1440)%1440;return String(Math.floor(total/60)).padStart(2,"0")+":"+String(total%60).padStart(2,"0")}
function node(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e}function button(text,className,handler){const e=document.createElement("button");e.type="button";e.className=className;e.textContent=text;e.addEventListener("click",handler);return e}
function renderPreview(){el.previewTitle.textContent=trip.title.trim()||"旅行名未設定";el.previewDate.textContent=formatDate(trip.date);el.countdown.textContent=countdownText(trip.date);el.timeline.replaceChildren();const has=trip.days.some(function(day){return day.schedules.some(function(s){return s.time||s.place.trim()})});el.empty.hidden=has;if(!has)return;trip.days.forEach(function(day,dayIndex){const filled=day.schedules.filter(function(s){return s.time||s.place.trim()});if(!filled.length)return;const section=node("section","preview-day");section.appendChild(node("h3","preview-day-title","DAY "+(dayIndex+1)));filled.forEach(function(s){const meta=TYPES[s.type]||TYPES.other;const item=node("div","preview-item");item.appendChild(node("div","preview-time",s.time||"--:--"));const line=node("div","preview-line");line.appendChild(node("span","preview-icon",meta.icon));item.appendChild(line);const content=node("div","preview-content");content.append(node("div","preview-place",s.place.trim()||"内容未入力"),node("div","preview-type",meta.label));item.appendChild(content);if(s.place.trim()){const map=document.createElement("a");map.className="map-link";map.textContent="🗺 地図";map.target="_blank";map.rel="noopener noreferrer";map.href="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(s.place.trim());item.appendChild(map)}section.appendChild(item)});el.timeline.appendChild(section)})}
function formatDate(value){if(!value)return"";const p=value.split("-");return p.length===3?p[0]+"年"+Number(p[1])+"月"+Number(p[2])+"日":value}
function countdownText(value){if(!value)return"";const p=value.split("-").map(Number);if(p.length!==3||p.some(Number.isNaN))return"";const today=new Date();today.setHours(0,0,0,0);const target=new Date(p[0],p[1]-1,p[2]);const days=Math.round((target-today)/86400000);return days>0?"出発まであと "+days+" 日":days===0?"本日出発！":"旅行終了"}
function switchView(view){document.querySelectorAll(".tab-button").forEach(function(b){b.classList.toggle("active",b.dataset.view===view)});document.getElementById("editPanel").classList.toggle("active",view==="edit");document.getElementById("previewPanel").classList.toggle("active",view==="preview");window.scrollTo({top:0,behavior:"smooth"})}
