const STORAGE_KEY="tabiwaku-v2";
const ACTIVE_KEY="tabiwaku-v2-active";
const TYPES={move:{label:"移動",icon:"🚗"},sight:{label:"観光",icon:"📍"},food:{label:"食事",icon:"🍴"},stay:{label:"宿泊",icon:"🏨"},other:{label:"その他",icon:"●"}};
const el={home:byId("homeView"),app:byId("appView"),shared:byId("sharedView"),tabs:byId("mobileTabs"),list:byId("tripList"),emptyTrips:byId("emptyTrips"),newTrip:byId("newTripButton"),homeLogo:byId("homeLogo"),title:byId("tripTitle"),date:byId("tripDate"),days:byId("daysEditor"),addDay:byId("addDayButton"),deleteTrip:byId("deleteTripButton"),previewTitle:byId("previewTitle"),previewDate:byId("previewDate"),countdown:byId("countdown"),emptyPreview:byId("emptyPreview"),timeline:byId("timeline"),status:byId("saveStatus"),copy:byId("copyShareButton"),line:byId("lineShareButton"),toast:byId("toast"),sharedTitle:byId("sharedTitle"),sharedDate:byId("sharedDate"),sharedCountdown:byId("sharedCountdown"),sharedTimeline:byId("sharedTimeline"),saveShared:byId("saveSharedButton")};
let trips=loadTrips();let activeId=null;let activeTrip=null;let sharedTrip=null;let statusTimer;
init();
function init(){bindStatic();const fromHash=readSharedHash();if(fromHash){showShared(fromHash);return}renderHome()}
function bindStatic(){el.homeLogo.addEventListener("click",showHome);el.newTrip.addEventListener("click",newTrip);el.addDay.addEventListener("click",function(){activeTrip.days.push(createDay());saveAndRender()});el.title.addEventListener("input",function(){activeTrip.title=el.title.value;saveAndPreview()});el.date.addEventListener("input",function(){activeTrip.date=el.date.value;saveAndPreview()});el.deleteTrip.addEventListener("click",deleteActiveTrip);el.copy.addEventListener("click",copyShareUrl);el.line.addEventListener("click",shareToLine);el.saveShared.addEventListener("click",saveSharedTrip);document.querySelectorAll(".tab-button").forEach(function(b){b.addEventListener("click",function(){switchView(b.dataset.view)})});window.addEventListener("hashchange",function(){const data=readSharedHash();if(data)showShared(data);else showHome()})}
function byId(id){return document.getElementById(id)}function uid(){return crypto&&crypto.randomUUID?crypto.randomUUID():Date.now()+"-"+Math.random().toString(16).slice(2)}
function createSchedule(time=""){return{id:uid(),type:"sight",time:time,place:"",memo:""}}function createDay(){return{id:uid(),schedules:[createSchedule()]}}function createTrip(){return{id:uid(),title:"",date:"",createdAt:Date.now(),updatedAt:Date.now(),days:[createDay()]}}
function normalizeTrip(t){if(!t||!Array.isArray(t.days))t=createTrip();t.id=t.id||uid();t.title=typeof t.title==="string"?t.title:"";t.date=typeof t.date==="string"?t.date:"";t.days=t.days.length?t.days:[createDay()];t.days.forEach(function(d){d.id=d.id||uid();d.schedules=Array.isArray(d.schedules)&&d.schedules.length?d.schedules:[createSchedule()];d.schedules.forEach(function(s){s.id=s.id||uid();s.type=TYPES[s.type]?s.type:"sight";s.time=typeof s.time==="string"?s.time:"";s.place=typeof s.place==="string"?s.place:"";s.memo=typeof s.memo==="string"?s.memo:""})});return t}
function loadTrips(){try{const data=JSON.parse(localStorage.getItem(STORAGE_KEY)||"[]");if(Array.isArray(data)&&data.length)return data.map(normalizeTrip)}catch(e){console.error(e)}const migrated=migrateLegacy();return migrated?[migrated]:[]}
function migrateLegacy(){for(const key of ["tabiwaku-v1-4","tabiwaku-v1-3","tabiwaku-v1-2","tabiwaku-v1-1"]){try{const raw=localStorage.getItem(key);if(raw)return normalizeTrip(JSON.parse(raw))}catch(e){}}return null}
function persist(){activeTrip.updatedAt=Date.now();const i=trips.findIndex(function(t){return t.id===activeTrip.id});if(i>=0)trips[i]=activeTrip;else trips.push(activeTrip);localStorage.setItem(STORAGE_KEY,JSON.stringify(trips));localStorage.setItem(ACTIVE_KEY,activeTrip.id);savedStatus()}
function savedStatus(){el.status.textContent="保存しました";clearTimeout(statusTimer);statusTimer=setTimeout(function(){el.status.textContent="自動保存"},900)}
function showHome(){history.replaceState(null,"",location.pathname+location.search);activeId=null;activeTrip=null;el.home.hidden=false;el.app.hidden=true;el.shared.hidden=true;el.tabs.hidden=true;renderHome();window.scrollTo(0,0)}
function renderHome(){el.list.replaceChildren();el.emptyTrips.hidden=trips.length>0;if(!trips.length)return;const sorted=[...trips].sort(sortTrips);sorted.forEach(function(t,index){const card=node("article","trip-card"+(index===0&&isFutureOrToday(t.date)?" trip-card-next":""));card.addEventListener("click",function(e){if(!e.target.closest("button"))openTrip(t.id)});if(index===0&&isFutureOrToday(t.date))card.appendChild(node("span","trip-badge","次の旅"));card.appendChild(node("h2","",t.title.trim()||"名称未設定"));card.appendChild(node("p","trip-card-date",formatDate(t.date)||"出発日未設定"));const cd=countdownText(t.date);if(cd)card.appendChild(node("p","trip-card-countdown",cd));const actions=node("div","trip-card-actions");actions.append(button("開く","button button-primary trip-open",function(){openTrip(t.id)}),button("×","button button-danger trip-delete",function(){deleteTrip(t.id)}));card.appendChild(actions);el.list.appendChild(card)})}
function sortTrips(a,b){const ad=a.date||"9999-12-31",bd=b.date||"9999-12-31";return ad.localeCompare(bd)||b.updatedAt-a.updatedAt}function isFutureOrToday(date){return date&&countdownDays(date)>=0}
function newTrip(){const t=createTrip();trips.push(t);localStorage.setItem(STORAGE_KEY,JSON.stringify(trips));openTrip(t.id)}
function openTrip(id){activeTrip=trips.find(function(t){return t.id===id});if(!activeTrip)return;activeId=id;el.home.hidden=true;el.shared.hidden=true;el.app.hidden=false;el.tabs.hidden=false;el.title.value=activeTrip.title;el.date.value=activeTrip.date;renderEditor();renderPreview();switchView("edit");window.scrollTo(0,0)}
function deleteTrip(id){if(!confirm("この旅を削除しますか？"))return false;trips=trips.filter(function(t){return t.id!==id});localStorage.setItem(STORAGE_KEY,JSON.stringify(trips));renderHome();return true}function deleteActiveTrip(){if(activeTrip&&deleteTrip(activeTrip.id))showHome()}
function saveAndRender(){persist();renderEditor();renderPreview()}function saveAndPreview(){persist();renderPreview()}
function renderEditor(){el.days.replaceChildren();activeTrip.days.forEach(function(day,dayIndex){const card=node("section","day-card"),heading=node("div","day-heading"),title=node("h3","","DAY "+(dayIndex+1)),actions=node("div","day-actions");if(activeTrip.days.length>1)actions.append(button("この日を削除","button button-danger",function(){activeTrip.days.splice(dayIndex,1);saveAndRender()}));heading.append(title,actions);const list=node("div","schedule-list");day.schedules.forEach(function(s,i){list.appendChild(renderEntry(day,s,i))});const add=button("＋ 予定を追加","button button-primary add-schedule-full",function(){const last=findLastTime(day);day.schedules.push(createSchedule(last?addMinutes(last,30):""));saveAndRender()});card.append(heading,list,add);el.days.appendChild(card)})}
function renderEntry(day,s,index){const entry=node("div","schedule-entry"),row=node("div","schedule-row");const type=document.createElement("select");type.className="schedule-type";Object.keys(TYPES).forEach(function(k){const o=document.createElement("option");o.value=k;o.textContent=TYPES[k].icon+" "+TYPES[k].label;o.selected=s.type===k;type.appendChild(o)});type.addEventListener("change",function(){s.type=type.value;saveAndPreview()});const minus=button("−","step-button minus",function(){s.time=addMinutes(s.time||"09:00",-15);saveAndRender()});const time=input("time","time-input",s.time,"時刻");time.step="300";time.addEventListener("input",function(){s.time=time.value;saveAndPreview()});const plus=button("＋","step-button plus",function(){s.time=addMinutes(s.time||"09:00",15);saveAndRender()});const place=input("text","schedule-place",s.place,"目的地・予定");place.placeholder="目的地・予定";place.addEventListener("input",function(){s.place=place.value;saveAndPreview()});const del=button("×","delete-button",function(){if(day.schedules.length===1){s.type="sight";s.time="";s.place="";s.memo=""}else day.schedules.splice(index,1);saveAndRender()});row.append(type,minus,time,plus,place,del);const memoRow=node("div","memo-row");memoRow.appendChild(node("span","memo-label","メモ"));const memo=document.createElement("textarea");memo.className="memo-input";memo.placeholder="予約名、駐車場、集合場所など";memo.value=s.memo;memo.addEventListener("input",function(){s.memo=memo.value;saveAndPreview()});memoRow.appendChild(memo);entry.append(row,memoRow);return entry}
function renderPreview(){el.previewTitle.textContent=activeTrip.title.trim()||"旅行名未設定";el.previewDate.textContent=formatDate(activeTrip.date);el.countdown.textContent=countdownText(activeTrip.date);renderTimeline(activeTrip,el.timeline,el.emptyPreview)}
function renderTimeline(trip,target,empty){target.replaceChildren();const has=trip.days.some(function(d){return d.schedules.some(hasContent)});if(empty)empty.hidden=has;if(!has)return;trip.days.forEach(function(day,dayIndex){const filled=day.schedules.filter(hasContent);if(!filled.length)return;const section=node("section","preview-day");section.appendChild(node("h3","preview-day-title","DAY "+(dayIndex+1)));filled.forEach(function(s){const meta=TYPES[s.type]||TYPES.other,item=node("div","preview-item");item.appendChild(node("div","preview-time",s.time||"--:--"));const line=node("div","preview-line");line.appendChild(node("span","preview-icon",meta.icon));item.appendChild(line);const content=node("div","preview-content");content.append(node("div","preview-place",s.place.trim()||"内容未入力"),node("div","preview-type",meta.label));if(s.memo.trim())content.appendChild(node("div","preview-memo",s.memo.trim()));item.appendChild(content);if(s.place.trim()){const map=document.createElement("a");map.className="map-link";map.textContent="🗺 地図";map.target="_blank";map.rel="noopener noreferrer";map.href="https://www.google.com/maps/search/?api=1&query="+encodeURIComponent(s.place.trim());item.appendChild(map)}section.appendChild(item)});target.appendChild(section)})}
function hasContent(s){return s.time||s.place.trim()||s.memo.trim()}
function sharePayload(){return{v:2,title:activeTrip.title,date:activeTrip.date,days:activeTrip.days.map(function(d){return{schedules:d.schedules.map(function(s){return{type:s.type,time:s.time,place:s.place,memo:s.memo}})}})}}
function makeShareUrl(){const json=JSON.stringify(sharePayload());const bytes=new TextEncoder().encode(json);let binary="";bytes.forEach(function(b){binary+=String.fromCharCode(b)});const encoded=btoa(binary).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");return location.origin+location.pathname+location.search+"#share="+encoded}
async function copyShareUrl(){const url=makeShareUrl();try{await navigator.clipboard.writeText(url);toast("共有URLをコピーしました")}catch(e){prompt("このURLをコピーしてください",url)}}
function shareToLine(){const url=makeShareUrl();const line="https://social-plugins.line.me/lineit/share?url="+encodeURIComponent(url);window.open(line,"_blank","noopener,noreferrer")}
function readSharedHash(){if(!location.hash.startsWith("#share="))return null;try{let encoded=location.hash.slice(7).replace(/-/g,"+").replace(/_/g,"/");while(encoded.length%4)encoded+="=";const binary=atob(encoded);const bytes=Uint8Array.from(binary,function(c){return c.charCodeAt(0)});return normalizeTrip(JSON.parse(new TextDecoder().decode(bytes)))}catch(e){console.error(e);toast("共有URLを読み込めませんでした");return null}}
function showShared(data){sharedTrip=data;el.home.hidden=true;el.app.hidden=true;el.tabs.hidden=true;el.shared.hidden=false;el.sharedTitle.textContent=data.title.trim()||"旅のしおり";el.sharedDate.textContent=formatDate(data.date);el.sharedCountdown.textContent=countdownText(data.date);renderTimeline(data,el.sharedTimeline,null);if(!el.saveShared.dataset.bound){el.saveShared.dataset.bound="1";el.saveShared.addEventListener("click",saveSharedTrip)}window.scrollTo(0,0)}
function saveSharedTrip(){if(!sharedTrip)return;const copy=normalizeTrip(JSON.parse(JSON.stringify(sharedTrip)));copy.id=uid();copy.createdAt=Date.now();copy.updatedAt=Date.now();copy.days.forEach(function(d){d.id=uid();d.schedules.forEach(function(s){s.id=uid()})});trips.push(copy);localStorage.setItem(STORAGE_KEY,JSON.stringify(trips));history.replaceState(null,"",location.pathname+location.search);toast("自分の旅に保存しました");openTrip(copy.id)}
function switchView(view){document.querySelectorAll(".tab-button").forEach(function(b){b.classList.toggle("active",b.dataset.view===view)});byId("editPanel").classList.toggle("active",view==="edit");byId("previewPanel").classList.toggle("active",view==="preview");window.scrollTo({top:0,behavior:"smooth"})}
function countdownDays(value){if(!value)return NaN;const p=value.split("-").map(Number);if(p.length!==3)return NaN;const today=new Date();today.setHours(0,0,0,0);return Math.round((new Date(p[0],p[1]-1,p[2])-today)/86400000)}function countdownText(v){const d=countdownDays(v);return Number.isNaN(d)?"":d>0?"出発まであと "+d+" 日":d===0?"本日出発！":"旅行終了"}function formatDate(v){if(!v)return"";const p=v.split("-");return p.length===3?p[0]+"年"+Number(p[1])+"月"+Number(p[2])+"日":v}function findLastTime(day){for(let i=day.schedules.length-1;i>=0;i--)if(day.schedules[i].time)return day.schedules[i].time;return""}function addMinutes(v,m){const p=v.split(":").map(Number),total=(p[0]*60+p[1]+m+1440)%1440;return String(Math.floor(total/60)).padStart(2,"0")+":"+String(total%60).padStart(2,"0")}function node(tag,c,text){const e=document.createElement(tag);if(c)e.className=c;if(text!==undefined)e.textContent=text;return e}function button(text,c,fn){const e=node("button",c,text);e.type="button";e.addEventListener("click",fn);return e}function input(type,c,value,label){const e=document.createElement("input");e.type=type;e.className=c;e.value=value;e.setAttribute("aria-label",label);return e}function toast(text){el.toast.textContent=text;el.toast.classList.add("show");setTimeout(function(){el.toast.classList.remove("show")},1800)}
